mysql_dsn: "username:password@tcp(host:port)/database"
postgres_dsn: "postgres://username:password@host:port/database"
tables:
  - source_table: "users"
    destination_table: "users"
  - source_table: "products"
    destination_table: "products"
